# Generated by Django 2.1.8 on 2019-05-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='region',
            field=models.CharField(max_length=40, verbose_name='지역'),
        ),
    ]
